### ISSUE TITLE
Bootloop infto fastboot after flashing generated boot.img

### ISSUE THREAD

**Issue by berbascum** [droidian-lavender/kernel-xiaomi-lavender#1]
Hello,

I have a Xiaomi lavender with a working Droidian using de boot.img from ubports and the last bookworm nightly from Dropidian repos.

I have tried to build this kernel source following the Droidian porting guide.

After a succesfully compilation, I have extracted the generated bootimage-4.4.192-*.deb package file and flashed the boot, dtbo and vbmeta imgs on the lavender (thw one with Droidian working that I have specified above)  from OrangeFox recovery ast version (11.1_2). The result is a bootloop into bootloader.
Also tried flashing over fastboot.
After reflashing the old ubports boot and dtbo, device boots again.

Once restored the working ubports boot and dtbo images, i can appreciate that:
  - When I flash only the boot.img generated by this kernel source, but mantaining old ubports dtbo, device bootlops into fastboot, but I can reboot to recovery with Vol+ key.
  - When I also flash dtbo.img, I cannot reboot to recovery unless I have flash again (using fastboot) the old ubports dtbo. In that case, I still in bootloop, but I can reboot to recovery again with Vol+ key.

I also tried compilation enabling kernel_dbt in boot.image as ubports kernel has it. But with the sme result.

Any help will be appreciated!

**Comment by berbascum** [comment]
I have been able to solve it.

The problem was on kernel image's dtb. I had replaced it with one from an older ubports lavender halium image using Yabit tool.

Now the kernel boots fine.

Thanks!

**Comment by sergiorgb** [comment]
Hi @berbascum can you give more information about what you did to insert the dtb into the boot.img, I'm on facing the same issue

**Comment by berbascum** [comment]
Hello Sergio,
The final solution is in my commit on this repo (only valid for lavender). With this changes the boot image should be correctly generated.
